GET http://localhost:3000/

###

GET http://localhost:3000/auth/users

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "Prashant Singh",
  "username": "prashant1k9",
  "password": "test"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "prashant1k9",
  "password": "test"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYXNoYW50MWs5IiwibmFtZSI6IlByYXNoYW50IFNpbmdoIiwiaWF0IjoxNjA4NDc2MTc5fQ.tHgzcqShxhPSoinMR1MMYxy_rkTfOjtJeP__EN9Jl2g"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYXNoYW50MWs5IiwibmFtZSI6IlByYXNoYW50IFNpbmdoIiwiaWF0IjoxNjA4NDc2MzcxLCJleHAiOjE2MDg0Nzk5NzF9.YZRDatvDnSRocbjL2U5m0cyJuJcZf2QnQeHmd1L2mIg